### ISSUE TITLE
Area2D should not be root node of KinematicBody

### ISSUE THREAD

**Issue by RailKill** [zeskysee/we-missed-party#21]
Some actors such as player and npc have Area2D as the root node, and a KinematicBody representing their bodies as a child node. Because all child nodes follow the transform of their parent node, it seems unintuitive even if the Area2D is static that the KinematicBody's positioning is based on the area's. It should either be the other way round if the area needs to follow the body, or have no parent-child relationship (separate from one another).

**Comment by zeskysee** [comment]
Fixed in commit 0c75a27b8ff4fce9cd34384674363a5b823a5cbb

**Comment by RailKill** [comment]
looks good 👍
