### ISSUE TITLE
White color font NPC count is not very visible

### ISSUE THREAD

**Issue by zeskysee** [zeskysee/we-missed-party#28]
White color font NPC count is not very visible

<img width="1792" alt="Screenshot 2022-04-03 at 6 08 44 PM" src="https://user-images.githubusercontent.com/6244226/161422444-e015b6c5-5d81-43fa-94bd-30e348113d2e.png">

**Comment by RailKill** [comment]
any idea what it should look like to make it more visible/nicer? mayb @z_z can have some input on this

**Comment by zeskysee** [comment]
from @z_z: use black color for icon and number and make it larger a little bit
