### ISSUE TITLE
Add skip instruction at intro & ending scene

### ISSUE THREAD

**Issue by zeskysee** [zeskysee/we-missed-party#29]
Add skip instruction at intro & ending scene at the top left side of intro & ending scene

<img width="1792" alt="Screenshot 2022-04-03 at 6 12 55 PM" src="https://user-images.githubusercontent.com/6244226/161422640-5b3424c4-4aff-4b8c-8ad4-7295f2d2b947.png">

**Comment by RailKill** [comment]
Already mostly implemented by #17, changes are in `dev` branch. To clarify, this issue is therefore for moving the skip instruction to the top-left (or it could stay in the middle, up to the implementer), and more importantly, to show it in the ending scene as well.

**Comment by zeskysee** [comment]
@z_z: put at the bottom left or bottom right for more visibility.

Text: (or better wording)
Press "`" to skip
